#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features='cxx test',
    source=['filter_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='filter_tests',
    use=['filter', 'gtest'])
